### ISSUE TITLE
When providing a wrong JSON Schema, the error raised during the validation of the message by the getHandler SQS contract is not explicit

### ISSUE THREAD

**Issue by hugoruy** [swarmion/swarmion#1190]
### Describe the bug

The json schema I provided for the validation of the message of getHandler for the SQS contract did not match the real messages schema. The error I got was not explicit : 
![image](https://github.com/swarmion/swarmion/assets/147498348/f71b8b87-a830-4772-9f02-1e90b904f7fe)

### Reproduction

The schema I used was close to : 

`const messageBodySchema = {
    type: 'object',
    properties: {
        Records: {
            type: 'array',
            items: {
                type: 'object',
                properties: {
                    body: xxx
                },
                required: ['body'],
            },
        },
    },
    required: ['Records'],
} as const satisfies JSONSchema;`

while the real message schema was `xxx`.

### System Info

```shell
System:
    OS: Linux 4.4 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
    CPU: (12) x64 13th Gen Intel(R) Core(TM) i7-1365U
    Memory: 3.11 GB / 15.66 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 16.20.2 - ~/.nvm/versions/node/v16.20.2/bin/node
    npm: 8.19.4 - ~/.nvm/versions/node/v16.20.2/bin/npm
    pnpm: 8.13.1 - ~/.local/share/pnpm/pnpm
```

### Validations

- [x] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't [already an issue](https://github.com/swarmion/swarmion/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CorentinDoue** [comment]
You didn't provide the real event you had as input and your schema is incomplete. I can't reproduce it. Can you provide more info about how you defined the trigger of the lambda. 

Can you also give me the version of ajv you have and how you created the `avj` singleton? 

There is no `.map` in the code near the schema validation. The only map I found so far is `Records.map(...)`. If it's `undefined` that means your input weren't a SQS event because SQS events always have a `Records` attribute

**Comment by clauzond** [comment]
We are using the latest version `ajv@8.12.0`.

It seems that this error triggers when the event has no attribute `Record`. When sending events without the attribute `Record`, the following error happens:

```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'map')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'map')",
        "    at Runtime.handler (/node_modules/.pnpm/@swarmion+serverless-contracts@0.32.0-alpha.1_@serverless+typescript@3.38.0_ajv@8.12.0_aws-cdk-lib@2.137.0/node_modules/@swarmion/serverless-contracts/index.js:1022:35)",
        "    at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1173:29)"
    ]
}
```

The error redirects to the following function in `index.js:1022:35`:
```
var getSQSHandler = (contract, options) => (handler) => {
  const internalOptions = {
    ...defaultOptions3,
    ...options
  };
  const recordsValidator = getRecordsValidator(contract, internalOptions);
  return async (event, context, callback, ...additionalArgs) => {
    const { Records } = event;
    const parsedRecords = Records.map( // line 1022
      parseRecord(internalOptions)
    );
    if (recordsValidator !== void 0 && !recordsValidator(parsedRecords)) {
      console.error("Error: Invalid records");
      console.error(JSON.stringify(recordsValidator.errors, null, 2));
      throw new Error("Invalid records");
    }
    if (internalOptions.handleBatchedRecords === false) {
      return handler({ records: parsedRecords }, context, callback, ...additionalArgs);
    }
    const allRecordsHandler = getAllRecordsHandler(
      // handleRecords is true, handler is SwarmionSQSHandler. Typescript is not able to infer this
      handler,
      context,
      callback,
      additionalArgs
    );
    return allRecordsHandler({ records: parsedRecords });
  };
};
```

**Comment by CorentinDoue** [comment]
If your event has no `Records` it's not a SQS event. This `getHandler` is made to be used in a lambda trigger by SQS events. I don't think we want to add a validation process that the event is a correct SQS event.

I will add a `logRawEvent` option to help debug those kinds of errors

**Comment by CorentinDoue** [comment]
I have been generous, I added a check that the `Records` params is present in the event, but I'm not sure I should have.
