### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by guillaumeduboc** [swarmion/swarmion#127]
Some links are broken in the documentation

![Kapture 2022-05-20 at 15 57 46](https://user-images.githubusercontent.com/33599414/169543918-6f71b281-f950-4919-8cd4-f5c5d9c2419c.gif)
 
This seems to happen only in prod, for links within the same folder

**Comment by fargito** [comment]
It seems the problem has disappeared 🤷🏻‍♂️
