### ISSUE TITLE
Jest Unit tests broken on CI when creating a new custom Library

### ISSUE THREAD

**Issue by Nyugue** [swarmion/swarmion#132]
Hi, at Kooalys, we encountered an issue that might also bother you.

We created a new lib in our Library folder.
In dev, no problem all tests are green, but as soon as we pushed it and ran tests in CI, we've got some : 
`Error: xxx/Xxxx/xxx.ts (1,30): error TS2307: Cannot find module '@kooalys/xxxx-xxx' or its corresponding type declarations.`
on all of our tests.

It took a bit of digging, but it seems that the issue originated from the yarn modules cache that was still hit in CI, even after the new library addition, because the cache key is a yarn.lock hash and this file has not been modified.

**Comment by guillaumeduboc** [comment]
@Nyugue we have simplified the CI now and this issue shouldn't happen anymore ! 

you can look at it if you want to update yours
