### ISSUE TITLE
Cannot find .code-workspace when generating a service/library with nx-plugin

### ISSUE THREAD

**Issue by StanHannebelle** [swarmion/swarmion#143]
Hi,

I tried to generate a new library with the nx-plugin but got the following error.

![image](https://user-images.githubusercontent.com/45121661/173073033-155ca1d3-a875-4e8a-9e20-e2938e2c66cd.png)

I get the same error when generating a new service.
Any ideas on how to solve that? 

Thanks!

**Comment by guillaumeduboc** [comment]
Have you specified a `npmScope` in your `nx.json` ?
We use it to resolve the name of the `.code-workspace` file as well as the imports from common packages
