### ISSUE TITLE
Fix lint on serverless-helpers

### ISSUE THREAD

**Issue by CorentinDoue** [swarmion/swarmion#145]
Le linter est cassé sur main pour le package serverless-helpers:
![Screenshot from 2022-06-10 17-08-03](https://user-images.githubusercontent.com/31917261/173095462-b3ddc52c-dc93-4c3d-8da7-5a2ff67e3332.png)

**Comment by fargito** [comment]
Thanks for reporting this? I can't reproduce the error on main though 🤔 
Are you on node16? We have made the switch a few days ago

**Comment by CorentinDoue** [comment]
Seems good with node 16
