### ISSUE TITLE
Fix CRITICAL & HIGH CVSE Security vulnerabilities

### ISSUE THREAD

**Issue by CorentinDoue** [swarmion/swarmion#1647]
### Describe the bug

![image](https://github.com/user-attachments/assets/56d47c33-38d2-41dc-9453-d14e729845e5)
https://github.com/swarmion/swarmion/security/dependabot

### Reproduction

https://github.com/swarmion/swarmion/security/dependabot

### System Info

```shell
All
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't [already an issue](https://github.com/swarmion/swarmion/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by CorentinDoue** [comment]
I think the critical is already fixed in the code because https://www.npmjs.com/package/json-schema-faker has been updated. 
But as the package has not been deployed the examples are still pointing to a version of swarmion which has vulnerabilities.

@guillaumeduboc can you make a release soon please 🙏

**Comment by guillaumeduboc** [comment]
v0.33.0 is released 🥳
