### ISSUE TITLE
[RFC] Automatic package upgrades

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#177]
We currently have to manally upgrade our packages. This is inefficient and time-consuming.

In order to do this, I have considered two solutions:
- [dependabot](https://github.com/dependabot): however, it currently does not support yarn3. See https://github.com/dependabot/dependabot-core/issues/1297
- [renovate](https://github.com/renovatebot/renovate) which seems to support yarn3

For the moment I would rather select Renovate for this reason, do you have other solutions?

**Comment by StanHannebelle** [comment]
After the migration of Swarmion from yarn v3 to pnpm, it looks like dependabot is not an option as it [doesn't support pnpm](https://github.com/dependabot/dependabot-core/issues/1736).

[renovate](https://docs.renovatebot.com/javascript/) does support pnpm.

This could be another solution: https://github.com/dependabot/dependabot-core/issues/1736#issuecomment-1181473557
