### ISSUE TITLE
Improve DevX with watch mode

### ISSUE THREAD

**Issue by guillaumeduboc** [swarmion/swarmion#196]
`yarn watch` on a specific package fails in both swarmion/swarmion and the published example

It seems the issue comes from the packaging of types

![Capture d’écran 2022-07-08 à 17 59 11](https://user-images.githubusercontent.com/33599414/178028404-ea33098d-cd89-48b1-a65c-7a0906ef303c.png)

**Comment by fargito** [comment]
Maybe this can help https://github.com/microsoft/TypeScript/issues/38365

**Comment by guillaumeduboc** [comment]
I cannot reproduce this issue, hence I am closing it
