### ISSUE TITLE
[Generators] `serverless-iam-roles-per-function` is referenced in `serverless.ts` but not installed

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#206]
Steps to reproduce:
- Start from a fresh install of Swarmion
- Run  `yarn generate-service my-service`
- Then `yarn deploy`

The deployment of the generated package fails with error:
```
       Error:
       Serverless plugin "serverless-iam-roles-per-function" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file. Run "serverless plugin install -n serverless-iam-roles-per-function" to install it.
```

We need to add it in the service package.json during the generation

**Comment by guillaumeduboc** [comment]
@fargito is there a reason for not using `serverless-iam-roles-per-function` in backend core ?
