### ISSUE TITLE
[FetchRequest] `getFetchRequest` doesn't allow undefined `baseUrl` 

### ISSUE THREAD

**Issue by Thomasprelot** [swarmion/swarmion#208]
At the moment, although it is not typed as required, `getFetchRequest` requires a `baseUrl` in its `options` argument : providing an empty object for `options` results in the following error : `Failed to construct 'URL': Invalid URL`.

This is because `getFetchRequest` creates a new URL and provide it to the `fetchFunction`. In the absence of the `baseUrl` option, it should only call the `fetchFunction` with the contract `path` as first parameter (the `fetchFunction` will then be responsible of adding the `baseUrl`).

Also, the `options` argument is always required in `getFetchRequest`. It could be optional and set to an empty object by default if no option is required.

**Comment by fargito** [comment]
Hello @Thomasprelot, thanks for opening this. Indeed this seems more logical. Is the `baseUrl` argument event relevant here? It seems to me that it could be directly passed in the `fetch` function, WDYT?

**Comment by Thomasprelot** [comment]
Good point, it seems more logical that the `fetch` function keeps the responsibility of the `baseUrl`.
However it might still be relevant to keep it in case we have no other need to use a custom `fetch` function, or in case we need to use multiple `baseUrl`s.
