### ISSUE TITLE
Upgrade Jest from 27 to 28

### ISSUE THREAD

**Issue by GuillaumeLagrange** [swarmion/swarmion#210]
Hello,

Here is a follow-up issue to our slack conversation so we can keep a track of things.

- Jest 28 integration has proven to be a bit painful as shown here: #198 and #199 
- However, the `serverless-cdk-plugin` package aims to use the `exports` feature of `package.json` to have multiple entry poins (necessary for serverless plugin particularities) -> #207 for more details
- Support for `exports` in jest has only been added in the v28
  - https://github.com/facebook/jest/issues/9771
  - https://jestjs.io/docs/upgrading-to-jest28#packagejson-exports

**Comment by GuillaumeLagrange** [comment]
Update, we closed #207 because #213 offers a more pragmatic solution for serverless-cdk-plugin.

Imo, the jest upgrade issue remains to be adressed, but in a less urgent fashion because we do not need it anymore :)

**Comment by fargito** [comment]
Closing this in favor of #245
