### ISSUE TITLE
`getFetchRequest` helper sets POST requests' Content-Type header as text/plain. Using getLambdaHandler with middy fails.

### ISSUE THREAD

**Issue by Eikix** [swarmion/swarmion#282]
Hi all, 
On the subject of serverless contracts, I've struggled with a cryptic issue 🤷.
 
Problem: `getFetchRequest` in `@swarmion/serverless-contracts` sets POST requests' Content-Type header as `text/plain`. When using `getLambdaHandler` to write a lambda handler, middy middleware enforces and validates `application/json` Content-Type header. 
On the frontend, when I make a POST request to my lambda with the above setup, it errors out. The resulting error does not give information over the problem.
Reference: https://www.swarmion.dev/docs/how-to-guides/use-serverless-contracts/api-gateway

I've struggled to understand clearly the difference between `getLambdaHandler` and `getHandler`. I've come to understand `getHandler` implements middleware of its own and accepts `text/plain` as a content-type header. 

Quick Solution:
- When using `getFetchRequest` to be able to type-safely call a lambda that uses serverless contracts, I've come to understand one MUST use `getHandler` helper from `@swarmion/serverless-helpers`.

Long-term solution:
- Recommend using `getHandler` in 99% of cases.
- Add `application/json` Content-Type header in `getFetchRequest` from `@swarmion/serverless-contracts`.

Thanks for your time:)! 

PS: Using serverless-contracts feels really good. Type-safety FTW! 🚀 🫡

**Comment by fargito** [comment]
That is correct @Eikix
