### ISSUE TITLE
Cannot read property X of undefined with optionnal queryStringParameters and API Gateway contract

### ISSUE THREAD

**Issue by LouisPinsard** [swarmion/swarmion#307]
Hello Swarmion team,

I have an issue with an ApiGatewayContract that uses queryStringParameters :
```
export const getMessagesContract = new ApiGatewayContract({
  id: 'get-messages',
  path: '/organization/{organizationSlug}/messages',
  method: 'GET',
  integrationType: 'httpApi',
  queryStringParametersSchema: {
    type: 'object',
    properties: {
      status: { type: 'string', enum: messageStatuses },
      audienceType: { type: 'string', enum: audienceTypeArray },
      messageType: { type: 'string', enum: messageTypes },
    },
    additionalProperties: false,
  },
  bodySchema: undefined,
  pathParametersSchema: {
    type: 'object',
    properties: {
      organizationSlug: { type: 'string' },
    },
    required: ['organizationSlug'],
    additionalProperties: false,
  } as const,
  headersSchema: undefined,
  authorizerType: 'jwt',
  outputSchema: {
    type: 'array',
    items: messageSchema,
  } as const,
});
``` 

In my frontend, I call my contract this way : 
```
const response = await getAxiosRequest(
        getMessagesContract,
        await createAuthClient(),
        {
          pathParameters: { organizationSlug: organization?.slug ?? '' },
          queryStringParameters: {
            status: fetchParams?.status,
            audienceType: fetchParams?.audienceType,
            messageType: fetchParams?.messageType,
          },
        },
      );

      return response.data;
    },
    {
      enabled,
    },
  );
``` 

When neither status, audienceType nor messageType are defined, the request sent by my frontend does not contain any queryStringParameters and thus the event.queryStringParameters is undefined in my lambda handler but it does not match with the type provided by swarmion (queryStringParameters is never undefined for swarmion).

**Comment by fargito** [comment]
Hello @LouisPinsard, I think Swarmion could fill `event.queryStringParameters` with an empty object in this case, WDYT?

**Comment by LouisPinsard** [comment]
@fargito I just saw the pull request by @Sc0ra, it seems more complicated than what you suggested.

I think always having an empty query string parameters object would have been more practical to consume ?

Tell me if I am wrong but, with the current fix, we will often have to write `event.queryStringParameters?.toto` with the question mark.

**Comment by fargito** [comment]
Indeed @LouisPinsard, I'll test the proposed implementation and then merge it.
