### ISSUE TITLE
Issues using `@swarmion/serverless-cdk-plugin`

### ISSUE THREAD

**Issue by adriencaccia** [swarmion/swarmion#316]
While trying to use `@swarmion/serverless-cdk-plugin`, I faced the following issues:

## Issues
1. The dependency `@types/serverless` is needed to have correct typing of `serverlessProps`. It is not installed when adding the dependency.

2. Change the [`myStackName` stack name](https://github.com/swarmion/swarmion/blob/85f2509e574337603e3c97c3267b5edbe71e5f0c/packages/serverless-cdk-plugin/src/serverlessCdk.ts#L81-L82) to something linked to the service

## Proposed solutions
1. Move the `@types/serverless` dependency of the `@swarmion/serverless-cdk-plugin` package to the `dependencies` properties instead of `devDependencies`

Issues specific to other bullet point tracked in #366 #367 #368

**Comment by GuillaumeLagrange** [comment]
Thanks for the issue!

This is not ideal, but in the meantime for anyone encountering this: the plugin should work despite the VSCode error.

**Comment by GuillaumeLagrange** [comment]
> 5. Change the [myStackName stack name](https://github.com/swarmion/swarmion/blob/85f2509e574337603e3c97c3267b5edbe71e5f0c/packages/serverless-cdk-plugin/src/serverlessCdk.ts#L81-L82) to something linked to the service

@adriencaccia This will require a deletion for existing stack if done naively.

I think I will provide an argument to override the name, with a breaking change warning to use this parameter set to the old name to avoid removing deployed services

**Comment by GuillaumeLagrange** [comment]
The points are being taken with the following priority

- [ ] @types/serverless dependency (point 1)
- [ ] Change the [myStackName stack name](https://github.com/swarmion/swarmion/blob/85f2509e574337603e3c97c3267b5edbe71e5f0c/packages/serverless-cdk-plugin/src/serverlessCdk.ts#L81-L82) to something linked to the service (point 5)
- [ ] Export a params helper similar to getCdkPropertyHelper (point 4)
- [ ] Improve getCdkPropertyHelper (point 3)
- [ ] VSCode bug -> eventually look for a quick fix (point 2)

**Comment by GuillaumeLagrange** [comment]
@adriencaccia I am splitting the bullet point not adressed by #324 across separate issues
