### ISSUE TITLE
getFetchRequest cannot handle error cases

### ISSUE THREAD

**Issue by Yoctoboy** [swarmion/swarmion#339]
Hey guys :)

We're using the `getFetchRequest` function to retrieve some data from an API we defined using a contract.

Problem is, in certain cases, our lambda will return an error (basically a string) instead of a correct JSON object.
And in `packages/serverless-contracts/src/contracts/apiGateway/features/fetchRequest.ts`, the function returns `response.json()`, which simply crashes when it gets a non-json object.

As a side note, this function also hides the status code of the response. In case of an error, I'd like to be able to get both the error string and error code.

With @fargito we thought we could discuss how to handle these cases here :)

**Comment by fargito** [comment]
@StanHannebelle since you are working on the errors

**Comment by StanHannebelle** [comment]
@Yoctoboy thanks for opening this issue.
We're currently working on adding errors in API Gateway contracts as well as handling different status codes.

You can follow progress on this topic in our roadmap (Errors in API Gateway contracts Card): https://github.com/orgs/swarmion/projects/1/

**Comment by fargito** [comment]
This will land in 0.25.0
