### ISSUE TITLE
Replace Serverless Framework with CDK

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#345]
## Migration plan

- We plan to make CDK the default IaC tool for deploying Serverless micro-services in Swarmion
- The goal is to have a starter usable in the next few weeks, the work is tracked in #351 
- Then during the first few months of January, we will go and implement the existing serverless contracts triggers on CDK, to have the same support on both frameworks

But we do not plan to deprecate the Serverless framework anytime soon 😃
Indeed, a lof (if not all) of our users are using SF, so we will keep supporting it!

**Comment by adriencaccia** [comment]
Hey @tainmar, we need to add more information on this issue 😅 

Until that, this is where things stand:
- We plan to make `CDK` the default IaC tool for deploying Serverless micro-services in Swarmion
- The goal is to have a starter usable in the next few weeks
- Then during the first few months of January, we will go and implement the existing serverless contracts triggers on CDK, to have the same support on both frameworks

But **we do not plan to deprecate the Serverless framework anytime soon** 😃 
Indeed, a lof (if not all) of our users are using SF, so we will keep supporting it!
