### ISSUE TITLE
Clarify the install documentation to use `pnpm`

### ISSUE THREAD

**Issue by guiyom-e** [swarmion/swarmion#348]
The doc of `swarmion/swarmion` propose to check the [template repository](https://github.com/swarmion/template) in which the command `yarn create swarmion-app` is proposed to install the project... but in fact only `pnpm` package manager can be used (see screenshot).

When checking the [user documentation](https://www.swarmion.dev/docs/getting-started/generate-your-first-swarmion-project#create-a-new-project-from-the-swarmion-template) ([source code](https://github.com/swarmion/swarmion/blob/main/user-docs/documentation/docs/getting-started/1-generate-your-first-swarmion-project.mdx)), the `npx create-swarmion-app my-project-name` is proposed, leading to the same error!

It should be great to :
- update the user documentation
- explain how to install `pnpm` (and maybe why it is the only package manager available): `npm install --global pnpm`
- deprecate `swarmion/template` repository if it is no more used, and update the swarmion documentation to unreference it

![image](https://user-images.githubusercontent.com/46320048/202759091-288f89bd-877d-43f9-83ad-9d2f06ca34f0.png)

**Comment by adriencaccia** [comment]
Thank you for the issue @guiyom-e 

You are right, we need to deprecate the https://github.com/swarmion/template repository and tell users to go to https://www.swarmion.dev.
And we need to update the doc to only reference `pnpm create swarmion-app`.

@fargito WDYT?
