### ISSUE TITLE
`ServerlessStack` resolved as `undefined` with `vitest`v0.26.2

### ISSUE THREAD

**Issue by guiyom-e** [swarmion/swarmion#419]
Since `vitest` v0.26.1 and v0.26.2, I have an error when running tests using the `ServerlessStack` construct from `@swarmion/serverless-cdk-plugin` v0.16.1 (latest)

When running a basic test (default one provided with swarmion):
```ts
describe('root service serverless.ts', () => {
  testFunctionNames(serverlessConfiguration);
});
```

I get this error:

```
        FAIL  serverless.test.ts [ serverless.test.ts ]
       TypeError: Class extends value undefined is not a constructor or null
        ❯ resources/CoreConstruct.ts:28:29
            28| class CoreConstruct extends ServerlessStack {
```
Where `CoreConstruct` is a CDK construct added in the serverless stack
 in `serverless.ts`:

```ts
custom: {
    cdkPlugin: {
      stack: CoreConstruct
    }
```

Note that this error is not raised with `vitest` v0.25 (tested on v0.25.8) and v0.26.0

**Comment by GuillaumeLagrange** [comment]
I can reproduce this when bumping vitest version, looking into it

**Comment by GuillaumeLagrange** [comment]
@guiyom-e is the issue still present when instead of

```typescript
import { ServerlessStack } from '@swarmion/serverless-cdk-plugin'

export class MyStack extends ServerlessStack {
  //...
}
```

You do

```typescript
import  ServerlessCdkPlugin from '@swarmion/serverless-cdk-plugin'

export class MyStack extends ServerlessCdkPlugin.ServerlessStack {
  //...
}
```

This seems to make the error disappear on my reproduction setup

**Comment by guiyom-e** [comment]
Bien vu !
No more error is raised. Quite not intuitive however :)

**Comment by fargito** [comment]
@GuillaumeLagrange does this need to be reflected in the docs? Otherwise I think we can close this issue

**Comment by GuillaumeLagrange** [comment]
The docs already contain the working syntax, I think we can close this and re-open if it ever becomes a problem
