### ISSUE TITLE
[RFC] Remove shared API Gateways

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#445]
This is kind of a philosophical matter, so I would like to have your advice.

The current practice in Swarmion is to generate an API Gateway in a `core` service, export it and then use it in all our services. We could label this as a "shared API Gateway".

However, this shared API Gateway creates a coupling point for our architectures. It has implications on the service generators, as well as the contracts structure.

In the microservices philosophy, our services should be as decoupled as possible. Therefore the shared API Gateway makes a lot less sense.

I would like for us to abandon this practice and instead create one API Gateway per service.

Downsides:
- our frontends would need to know several API Gateways (but we could also set a master API Gateway in front, whose only job would be to route between these API Gateways)

Advantages:
- our services will be more decoupled
- our service generator much simpler and reusable

In order to achieve this, we should:
- change the examples
- change the create-swarmion-app
- edit the documentation (and especially the "Getting started" docs)
- update the generators

WDYT? @adriencaccia @Sc0ra @guillaumeduboc @GuillaumeLagrange @StanHannebelle

**Comment by GuillaumeLagrange** [comment]
Wouldnt having one API gateway routing trafic to the propper API gateway double the cost of each request ? I believe API Gateway is already one of the more expensive services that we use.

**Comment by fargito** [comment]
Yes, that is correct, but that wouldn't be mandatory. The two alternatives I can see are:
- at build time, the frontend gets all the urls it needs
- each API Gateway uses a subdomain of the API domain, and therefore it is completely predictable

**Comment by fargito** [comment]
Let's go for shared resources
