### ISSUE TITLE
Make the root `test` target use sub targets' nx cache

### ISSUE THREAD

**Issue by GuillaumeLagrange** [swarmion/swarmion#448]
Currently, if we run

`pnpm test-linter` at the root of the workspace, then run `pnpm test`, the `test` target does not make use of the `test-linter` nx cache.

We could remove the `test` target in workspaces, and keep the `test` target in root, which would only call 
```
 nx run-many --targets=test-linter,test-type,test-circular,test-unit --all
```
[relevant nx example (last one)](https://nx.dev/packages/nx/documents/run-many#examples)

What do you think ?

**Comment by fargito** [comment]
That is a good point. However, I often use the `test` target in workspaces, and I believe it can be useful.

We could instead use the Nx `test-*` targets to build the `test` target inside workspaces, and remove the `test` target from `nx.json` to prevent the cache to be stored twice. 

WDYT?

**Comment by adriencaccia** [comment]
> We could instead use the Nx test-* targets to build the test target inside workspaces, and remove the test target from nx.json to prevent the cache to be stored twice.

@fargito I do not really understand the implications, how will this work? Could you write a quick example of what this will look like?

**Comment by fargito** [comment]
I would mean for example in the `package.json` in `serverless-helpers`, set `"test": "nx run-many --targets=test-linter,test-type,test-circular,test-unit --project=serverless-helpers"`.

That way we can still use the `test` target in the packages with the same configuration.

WDYT?

**Comment by guillaumeduboc** [comment]
Same as @fargito I use `test` target in the projects quite a lot
His solution requires that we specify in every package.json the name of the project associated with that package.json which is quite constraining

We could instead make use of `nx run` and define : 
``` 
"test": "nx run test-linter && nx run test-type && nx run test-unit && nx run test-circular"
```

wdyt?

**Comment by fargito** [comment]
That would be even better @guillaumeduboc !
