### ISSUE TITLE
`getFetchRequest` example doesn't resolve the correct URL

### ISSUE THREAD

**Issue by guillaumeduboc** [swarmion/swarmion#464]
### Issue
`getFetchRequest` is not resolving the proper url

### Reproduction

Create a contract following the tutorial and use a `getFetchRequest`.
```typesctipt
const getUserContract = new ApiGatewayContract({
  id: 'users-getUser',
  path: '/users/{userId}',
  method: 'GET',
  integrationType: 'httpApi',
  pathParametersSchema,
  outputSchema: userEntitySchema,
});
```

use `https://toto.com/tata` or `https://toto.com/tata/` as a `baseUrl`

The `getFetchRequest` will try to fetch the url `https://toto.com/users/{userId}`

**Comment by guillaumeduboc** [comment]
### Reason

This is due to the behavior of the URL module. 

```typescript

new URL('/users/{userId}', 'https://toto.com/tata')   // will return https://toto.com/users/{userId}

new URL('/users/{userId}', 'https://toto.com/tata/')  // will return https://toto.com/users/{userId}

new URL('users/{userId}', 'https://toto.com/tata')   // will return https://toto.com/users/{userId}


new URL('users/{userId}', 'https://toto.com/tata/')   // will return https://toto.com/tata/users/{userId}
```


We don't have this issue with `getAxiosRequest` because axios use their own rule to [combine the url](https://github.com/axios/axios/blob/d83316db4a242252db3a2ed7728cb43f8f8f4189/dist/axios.js#L1872-L1875)


### Quick fix

When using the contract, remove the leading slash in path and add a trailing slash on baseUrl

### Long term fix

use the same combine url as axios to concatenate baseUrl and path before transforming it into a URL object
WDYT ?

**Comment by adriencaccia** [comment]
Hey @guillaumeduboc, I agree with the long-term fix you proposed. We should have unit tests that assure that the URL is resolved correctly.

PRs are welcome!
