### ISSUE TITLE
Update to the latest Nx configuration

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#539]
with Nx version 15.17.0, I have the following message when running commands:
```bash
   Nx no longer reads configuration from workspace.json.
   Run "nx g @nrwl/workspace:fix-configuration" to split workspace.json into individual project.json files.
```
We need to:
- [ ] apply this change on the main repo and the examples
- [ ] update the generators

**Comment by adriencaccia** [comment]
A small [migration guide](https://nx.dev/deprecated/workspace-json#workspace.json) that could be useful

**Comment by fargito** [comment]
Oh, based on this guide, I think we can just remove the `workspace.json` file entirely

**Comment by adriencaccia** [comment]
> Oh, based on this guide, I think we can just remove the `workspace.json` file entirely:
> 
> > If every project is listed as a string, instead of an object with project configuration properties, then it is safe to delete the workspace.json file.

Yep, I opened the draft PR #540. I just ran `nx migrate latest` and `nx g @nrwl/workspace:fix-configuration` and it did everything automatically.
I will continue the PR later today with modifications to `nx-plugin` and the examples.
