### ISSUE TITLE
Require examples check to pass before validating the merge group

### ISSUE THREAD

**Issue by fargito** [swarmion/swarmion#542]
We now have activated the check-examples in the merge group, however the merge group finishes before they are green.

I think it is because the examples are not required for the merge to main.

We need to add them

**Comment by guillaumeduboc** [comment]
We might need to update the job
for the moment it is not always run, and requiring a job that doesn't run will block our queue

**Comment by fargito** [comment]
That is right

**Comment by Sc0ra** [comment]
Fixed by #618
