### ISSUE TITLE
[RFC] Improve distribution of `serverless-contracts`

### ISSUE THREAD

**Issue by GuillaumeLagrange** [swarmion/swarmion#551]
# Why
`@swarmion/serverless-contracts` as a package is used by both frontend and backend services.  
While our recommendations make sure everything is tree-shaken, we could benefit from a smarter split 

Other related subjects
  - `pnpm` peerDependency resolution stability
  - quality gate on lambda bundle size (cdk-bundle-analyzer)
  - quality gate on dist contract size

**Comment by GuillaumeLagrange** [comment]
# Proposition
Split `@swarmion/serverless-contracts` into three packages
- `@swarmion/serverless-contracts-core`: holds all the abstract definition of what a contract is, provides tool to create contracts, typically used by app's contract packages
- `@swarmion/serverless-contracts-consumer`: holds all the abstract definition of what a contract is, provides tool to create contracts, typically used by app's contract packages

**Comment by adriencaccia** [comment]
Hey @GuillaumeLagrange, regarding the yet undocumented proposition of keeping a single package with `exports`, this should interest you: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler

Basically, with this new `--moduleResolution: bundler`, TypeScript users can benefit from the `exports` without all the previous cumbersome changes.
