### ISSUE TITLE
Add `@swarmion/integration-tests` with `TestEnvVar` & `syncTestEnvVars`

### ISSUE THREAD

**Issue by CorentinDoue** [swarmion/swarmion#564]
## Part 1 of https://github.com/swarmion/swarmion/issues/525

Concretely I want to open source the code I did with @MaximeVivier to help manage the integration test environment variables. 
The interface will be something like

```ts 
// cdk stack
stack.node.setContext(SCOPE_CONTEXT_NAME, 'myScope');
// ...
// latter in a construct
new TestEnvVar(this, "API_URL", { value: httpApi.url }); // => create a SSM parameter /testEnvVar/myScope/API_URL
```

```ts
// setup file of the test runner 
await syncTestEnvVars({ scope: 'myScope' }); // get /testEnvVar/myScope/API_URL from SSM or cache and push it into process.env.API_URL
```

```ts
// integration test file

describe("health check", () => {
  it("returns 200", async () => {
    const response = await axios.get(`${TestEnvVars.API_URL}/health`);
    expect(response.status).toBe(200);
  });
});

```

The env vars can be scoped thank a string parameter to avoid importing all of them in the integration tests

`TestEnvVar` also creates & syncs a ts file to get the declared variable types. This file can be committed.

**Comment by fargito** [comment]
This looks good @CorentinDoue! However we need to ensure that the variable name is scoped to the service name in order to avoid collision between services.

Maybe something like:
```ts
// cdk stack
new TestEnvVar(this, "API_URL", { value: httpApi.url }); // => create a SSM parameter /testEnvVar/<stackName>/API_URL
```

WDYT?

**Comment by CorentinDoue** [comment]
Yes it's what I'm doing actually. I didn't update the comment

**Comment by fargito** [comment]
Great!
