### ISSUE TITLE
`syncEnvVarType` is broken

### ISSUE THREAD

**Issue by CorentinDoue** [swarmion/swarmion#585]
When I use `@swarmion/integration-tests` on Canopia the `syncEnvVarType` util is broken:

```
yarn sls deploy

Error while trying to sync config types: [TypeError] (0 , import_traverse.default) is not a function
```
This is the problem of compatibility between @babel/traverse and ESM: https://github.com/babel/babel/issues/13855

I suppose, it worked on Canopia before because the package was bundled with the old method (babel + cjs first). 

Now `@swarmion/integration-tests` is bundled with tsup and is ESM first 

=> I suppose node load the package as ESM when I run `sls deploy`

Versions:

- Node: `14.18.1`
- Sls framework: `3.25.0`
- `@swarmion/integration-tests`: `0.26.0-alpha.0`

**Comment by adriencaccia** [comment]
@CorentinDoue I found a band aid fix in [`96a6bca` (#578)](https://github.com/swarmion/swarmion/pull/578/commits/96a6bcad45df39b295da47be28dfae0f760aad53)

**Comment by CorentinDoue** [comment]
Did you check it still work with cjs too ?

**Comment by adriencaccia** [comment]
When using commands like `cdk synth`, the `main` field script is loaded, so the `index.cjs` file will be loaded. This one worked on my project.
