### ISSUE TITLE
Make directory dependencies in another repo work with the `watch` command

### ISSUE THREAD

**Issue by adriencaccia** [swarmion/swarmion#587]
## The issue

When trying to locally use a library packaged with the swarmion configuration in another app, using [directory dependencies](https://pnpm.io/pnpm-vs-npm#directory-dependencies) with `pnpm add file:../../my-swarmion-app/packages/my-package`, there is an issue where modified code is not reflected in the app although the `watch` command is running in the package.

## To locally use a package from a swarmion app in another app, the following steps are taken

1. Run `pnpm watch` in the package directory. This will clean (remove) the `dist` folder, re-create it and listen for changes.
2. Run `pnpm add file:...` in the app directory. A symlink of the whole package is created to the app's `node_modules` folder, including the package's `dist` folder.
3. Make a change to the package source code, modifying the `dist` folder with the new code.
4. The modified code is not reflected in the app.

The problem is that at step 3, `tsup` will delete the `dist` folder because of the `clean: true` config option. Thus breaking the symlink created to the app's `node_modules`. The changes will not be reflected.

## Solution

Remove `clean: true` from the `tsup.config.ts` files, as the `dist` folder is already cleaned when it matters, ie. when runnning `package` and `watch` commands.

**Comment by guillaumeduboc** [comment]
Great proposition ! 

To recreate the symlink in the app's `node_modules`, the  the complete command would be `pnpm rm package && pnpm add file:...`
