### ISSUE TITLE
Cannot deploy example in us-east-2 but successful in us-east-1

### ISSUE THREAD

**Issue by ktwbc** [swarmion/swarmion#627]
### Describe the bug

Attempting to deploy swarmion-full-stack will fail on the frontend-dev step, and the cloudformation deployment in progress will fail on attempting to set S3BucketPolicy with an error 

2023-04-18 21:25:18 UTC-0500 | appBucketPolicyE4A812A9 | CREATE_FAILED | API: s3:PutBucketPolicy Access Denied
-- | -- | -- | --

This happens on an account where Block Public Access for S3 is set by default (which is now the default as of April 2023 https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html)

### Reproduction

Start within the swarmion-full-stack examples folder
set SharedConfig to use region us-east-2
run build and deploy

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 1.42 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 16.17.0 - /opt/homebrew/opt/node@16/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - /opt/homebrew/opt/node@16/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 94.0.2
    Safari: 16.4
  npmPackages:
    @swarmion/nx-plugin: ^0.27.0 => 0.27.0
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't [already an issue](https://github.com/swarmion/swarmion/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ktwbc** [comment]
So I thought it was related to region, actually that is not the issue. What's happening is the account I am testing on has security where the S3 buckets cannot be made public, via the AWS policy that disables public access.

The policy being created by the sample has the Principle set as AWS:*

```
{
			"Effect": "Allow",
			"Principal": {
				"AWS": "*"
			},
			"Action": "s3:GetObject",
			"Resource": "arn:aws:s3:::swarmion-full-stack-frontend-de-appbucket672f90f4-zyvcylt214rn/*"
		}
```

And because that is opening up the bucket to the world, the API action is not allowing that, hence the error

Your bucket policy changes can’t be saved
You either don’t have permissions to edit the bucket policy, or your bucket policy grants a level of public access that conflicts with your Block Public Access settings. To edit a bucket policy, you need s3:PutBucketPolicy permissions. To review which Block Public Access settings are turned on, view your account and bucket settings. Learn more about Identity and access management in Amazon S3 
API response
Access Denied

The exact same error happens if I try to go into a bucket and set that policy manually in the S3 console, but if I set the Principle to a specific role, it works. 

This means the underlying issue is that example is just being too permissive on its example because since it is setting up buckets with cloudfront, there's no reason the bucket itself should be open to the world.

**Comment by ktwbc** [comment]
So this may not even be your issue. You're relying on serverless-lift and the construct static-web-site which is setting the permissions to be open, not in your framework directly.

**Comment by adriencaccia** [comment]
Hey @ktwbc, thank you for your interest in swarmion 😉 

Great job on the investigation! As you said, the public bucket comes from the https://github.com/getlift/lift `static-website` construct. And in this construct the bucket is publicly available.

However, I am actually the one that created the other construct [`single-page-app`](https://github.com/getlift/lift/blob/master/docs/single-page-app.md) that does essentially the same thing as the `static-website`, with the difference that it is tailored for SPA that have a single entry-point. Moreover, in this construct, the bucket is not publicly available 🎉 

So you can use `single-page-app` instead `static-website` to comply with your team's security!

Furthermore, I think this a good change for the `full-stack` example, as we are indeed deploying a SPA, I'll reopen the issue to track it.

**Comment by ktwbc** [comment]
Ah --- well I added a bug on the lift project yesterday too because I don't think it's our company security directly, it's the AWS change made this month where the blocked access is now the default when a new bucket is created unless the construct specifically overrides it. I got the same failure on a personal AWS account.
