### ISSUE TITLE
Add option to return validation error instead of "Invalid input" when the body doesn't match the bodySchema of the ApiGatewayContract

### ISSUE THREAD

**Issue by clementmarcilhacy** [swarmion/swarmion#629]
### Clear and concise description of the problem

As a developer using Swarmion I want see the validation errors like in cloudwatch when I try to access an API with a body that doesn't match the bodyScham instead of a raw string "Invalid input" so that the consumers of my API know what is wrong.

### Suggested solution

add a flag named `returnValidationErrors` and return validation errors if this flag is activated instead of "Invalid input"

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by adriencaccia** [comment]
Fixed in #630
