### ISSUE TITLE
Typescript lint errors on sample code

### ISSUE THREAD

**Issue by ktwbc** [swarmion/swarmion#636]
### Describe the bug

The sample code for services/users/functions/getUser/handler.ts (among others) is being flagged by linting for Invalid Overload and other errors. Unclear if this is a setting issue or improper coding

```
import { getUserContract } from '@swarmion-full-stack/users-contracts';
import { getHandler, HttpStatusCodes } from '@swarmion/serverless-contracts';
import Ajv from 'ajv';

const ajv = new Ajv();

export const main = getHandler(getUserContract, { ajv })(async (event) => {
  const { userId } = event.pathParameters;

  await Promise.resolve({ userId });

  return {
    statusCode: HttpStatusCodes.OK,
    body: { userId: userId, userName: 'hello_world' }
  };
});
```
<img width="875" alt="Screenshot 2023-04-22 at 10 57 27" src="https://user-images.githubusercontent.com/624611/233795010-bf97732b-a964-4493-86a5-a665013246b1.png">
<img width="800" alt="Screenshot 2023-04-22 at 10 57 34" src="https://user-images.githubusercontent.com/624611/233794880-c8249ac6-210c-44dd-aaec-171a7133fa39.png">

### Reproduction
I tested this in Webstorm but also happening in VSCode
Load Using WebStorm 
WebStorm 2022.3.4
Build #WS-223.8836.50, built on March 15, 2023

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 848.22 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 9.5.1 - /opt/homebrew/opt/node@18/bin/npm
  Browsers:
    Chrome: 112.0.5615.137
    Firefox: 94.0.2
    Safari: 16.4
```

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/swarmion/swarmion/blob/main/CONTRIBUTING.md).
- [X] Read the [docs](https://www.swarmion.dev/docs/).
- [X] Check that there isn't [already an issue](https://github.com/swarmion/swarmion/issues) that reports the same bug to avoid creating a duplicate.
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by adriencaccia** [comment]
Hey @ktwbc, thanks for the issue.

We thought we had already fixed that problem, but it seems it keeps happening 😩 
The cause is multiple versions of `ajv` involved with conflicting interfaces.

A quick fix is to install the `8.6.3` version of `ajv` in the users package: 
![image](https://user-images.githubusercontent.com/19605940/233855613-a6eeadbc-f490-49bc-9351-65ae31457add.png)

We should go and look at why our automated tests do not fail, and think of a long-term solution.

**Comment by ktwbc** [comment]
Thanks. Can I ask a quick guidance question on this? In serverless framework normally I would pass a stage as --stage= to determine the environment to deploy, for example --stage=qa which would use qa environment files. I'm unclear when using the nx deploy which filters to the serverless core/user projects how you would determine which environment? I can see in in sharedParams where I can define additional environments but cannot see how this connects to serverless. Should I be making copies of the deploy script command in the root parent.json like deploy-qa and just appending --stage=qa there?

**Comment by adriencaccia** [comment]
Yes that's the idea.
That is what is done by the `deploy-staging` and `deploy-production` scripts, both in the [package.json files of services](https://github.com/swarmion/swarmion/blob/9acd34128a132a3a9796d5ab692a70f67b73061a/examples/swarmion-full-stack/services/core/package.json#L9) and the [`nx.json` root config file](https://github.com/swarmion/swarmion/blob/7047208657cfbbf70956b4039232407c67d41125/examples/swarmion-full-stack/nx.json#L39).
You can adapt those to better suit the same of your different stages.

**Comment by ktwbc** [comment]
Ok thanks. Just trying to reconcile different terms in various places, stage vs target vs mode vs NODE_ENV with not a lot of clarity or documentation on what's affecting what.

**Comment by adriencaccia** [comment]
No worries!
If you think of any documentation tweaks, and/or missing things, let us know.

**Comment by Sc0ra** [comment]
Hello @ktwbc 
Doing some cleanup in the issues, do you still have any problem regarding this issue or could I close it ?

**Comment by ktwbc** [comment]
It's good thank you!
